# Generated by Django 5.0.1 on 2024-04-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
