# Generated by Django 5.0.1 on 2024-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_appointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
