# Generated by Django 5.0.1 on 2024-03-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_appointment_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='appointment_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.appointment'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
