# Generated by Django 5.0.1 on 2024-03-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_prescribedmedicine_prescription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='gender',
            field=models.CharField(default='rather not say', max_length=20),
        ),
    ]
