# Generated by Django 5.0.1 on 2024-03-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_prescription_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
