# Generated by Django 5.0.1 on 2024-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_prescription_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
