# Generated by Django 5.0.1 on 2024-03-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor_profile_img_alter_patient_profile_img'),
        ('doctor', '0010_bill_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
            ],
        ),
    ]
