# Generated by Django 5.0.1 on 2024-03-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='endtime',
        ),
    ]
