# Generated by Django 5.0.1 on 2024-03-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_remove_timeslot_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='is_available',
            field=models.CharField(default='available', max_length=12),
        ),
    ]
