# Generated by Django 5.0.1 on 2024-04-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_timeslot_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='billmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.bill')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.medicine')),
            ],
        ),
    ]
